[tool.poetry]
    authors = ["Paradox Engineer <engineering@paradox.ai>"]
    classifiers = [
        "Programming Language :: Python :: 3.10.4",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ]
    description = "Paradox python dev dependencies."
    homepage = "https://olivia.paradox.ai"
    keywords = ["Paradox", "Olivia", "Artificial Intelligence"]
    license = "BSL-1.0"
    maintainers = ["PhuongTMR <phuong.nguyen@paradox.ai>"]
    name = "paradox-pydevdeps"
    packages = [{include = "styleguide"}]
    readme = "README.md"
    repository = "https://github.com/ParadoxAi/paradox-pydevdeps"
    version = "1.0.1"

    [tool.poetry.dependencies]
        python = "^3.10.4"

        bandit      = ">=1.7.2"
        curlify     = ">=2.2.1"
        flake8      = ">=4.0.1"
        ipython     = ">=8.0.1"
        jedi        = ">=0.18.1"
        pep8-naming = ">=0.12.1"
        pre-commit  = ">=2.17.0"
        pyright     = ">=1.1.245"
        virtualenv  = ">=20.13.1"

        django-coverage-plugin  = "^2.0"
        django-debug-toolbar    = "^3.3"
        django-extra-checks     = "^0.12"
        django-migration-linter = "^4.1"
        django-querycount       = "^0.7"
        django-test-migrations  = "^1.2"


        flake8-bugbear             = "^22.7.1"
        flake8-django              = "^1.1"
        flake8-docstrings          = "^1.6.0"
        flake8-implicit-str-concat = "^0.3.0"
        flake8-pytest-style        = "^1.6"
        wemake-python-styleguide   = "^0.16.1"

        nitpick        = "^0.32"
        requests-cache = "0.9.5"

        pytest              = "^7.1"
        pytest-cov          = "^3.0"
        pytest-deadfixtures = "^2.2"
        pytest-django       = "^4.5"
        pytest-factoryboy   = ">=2.1.0"
        pytest-randomly     = "^3.11"
        pytest-testmon      = "^1.3"
        pytest-timeout      = "^2.1"

        pytest-html  = ">=3.1.1"
        pytest-mock  = ">=3.6.1"
        pytest-xdist = ">2.4.0"

        faker = ">=13.12.1"

        hypothesis = "^6.47.0"
        nplusone   = "^1.0"

        doc8                     = "^0.11"
        sphinx                   = "^5.0.1"
        sphinx-autodoc-typehints = "^1.18"
        tomlkit                  = "^0.11.0"

        dennis        = "^0.9"
        dotenv-linter = "^0.3"
        dump-env      = "^1.3"
        polint        = "^0.4"
        safety        = "^1.10"
        yamllint      = "^1.26"

[build-system]
    build-backend = "poetry.core.masonry.api"
    requires      = ["poetry-core>=1.0.0"]
