# `nitpick` specific configuration.
# `nitpick` ensures that you have the same configuration
# in your own project.

# Make sure to install it with:
# `pip install nitpick`

# See: https://nitpick.readthedocs.io/en/latest/

# This file is included into base-preset.

# Follow Flask's flake8 guide https://github.com/pallets/flask/blob/main/setup.cfg#L64
# Add Django and Pytest plugins

["setup.cfg".flake8]
    min_python_version = "3.10.0"
    max-complexity  = 20
    max-line-length = 120

    # exclude sources
    exclude = ".git,__pycache__,.venv,.eggs,*.egg,build,.build,dist,.tox,poetry_scripts"

    # B = bugbear
    # E = pycodestyle errors
    # F = flake8 pyflakes
    # W = pycodestyle warnings
    # B9 = bugbear opinions
    # ISC = implicit str concat
    # DJ = django
    # PT = pytest
    select = "B,E,F,W,B9,ISC,DJ,PT"

    ignore = "E203,E402,E501,E722,W503,PT001,PT023"
