# `nitpick` specific configuration.
# `nitpick` ensures that you have the same configuration
# in your own project.

# Make sure to install it with:
# `pip install nitpick`

# See: https://nitpick.readthedocs.io/en/latest/

# This file is included into base-preset.

["setup.cfg".flake8]
    format      = "paradox"
    show-source = true

    # Plugins:
    max-complexity  = 6
    max-line-length = 120

    # darglint:
    docstring-style = "numpy"

    # Violations:
    ignore = "D100,D104,D401,W504,RST303,RST304,DAR103,DAR203"
