# Styles file for nitpick

[nitpick]
    minimum_version = "0.32.0"

    [nitpick.styles]
        include = [
            "file-structure.toml",
            "flake8.toml",
            "isort.toml",
            "pydocstyle.toml",
            # "mypy.toml",
            "poetry.toml"
        ]
