# `nitpick` specific configuration.
# `nitpick` ensures that you have the same configuration
# in your own project.

# Make sure to install it with:
# `pip install nitpick`

# See: https://nitpick.readthedocs.io/en/latest/

[nitpick.files.present]
    "pyproject.toml" = "Install poetry and run 'poetry init' to create it"

["pyproject.toml".tool.poetry.dev-dependencies]
    bandit      = ">=1.7.2"
    curlify     = ">=2.2.1"
    flake8      = ">=4.0.1"
    ipython     = ">=8.0.1"
    jedi        = "0.17.2"
    pep8        = ">=1.7.1"
    pep8-naming = ">=0.12.1"
    pre-commit  = ">=2.17.0"
    pycodestyle = ">=2.8.0"
    pydocstyle  = ">=6.1.1"
    pyflakes    = ">=2.3.1"
    virtualenv  = ">=20.13.1"

    django-coverage-plugin  = "^2.0"
    django-debug-toolbar    = "^3.3"
    django-extra-checks     = "^0.11"
    django-migration-linter = "^4.1"
    django-querycount       = "^0.7"
    nplusone                = "^1.0"

    flake8-django            = "^1.1"
    flake8-logging-format    = "^0.6"
    flake8-pytest-style      = "^1.6"
    wemake-python-styleguide = "^0.16"

    django-test-migrations = "^1.2"
    hypothesis             = "^6.46"
    pytest                 = "^7.1"
    pytest-cov             = "^3.0"
    pytest-deadfixtures    = "^2.2"
    pytest-django          = "^4.5"
    pytest-randomly        = "^3.11"
    pytest-testmon         = "^1.3"
    pytest-timeout         = "^2.1"

    django-stubs = "^1.10"
    mypy         = "^0.942"

    doc8                     = "^0.11"
    sphinx                   = "^4.5"
    sphinx-autodoc-typehints = "^1.18"
    tomlkit                  = "^0.10"

    dennis        = "^0.9"
    dotenv-linter = "^0.3"
    dump-env      = "^1.3"
    polint        = "^0.4"
    safety        = "^1.10"
    yamllint      = "^1.26"
