# Paradox preset

["setup.cfg".flake8]
    format      = "paradox"
    show-source = true

    # Plugins:
    max-complexity  = 6
    max-line-length = 120

    # darglint:
    docstring-style = "numpy"

    # Violations:
    ignore = "D100,D104,D401,W504,RST303,RST304,DAR103,DAR203"

["setup.cfg".isort]
    line_length = 120

[nitpick.files."setup.cfg"]
    comma_separated_values = ["flake8.ignore"]
