name: GITHUB - Auto tag version
on:
  push:
    branches:
      - master
jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Bump & tag new version
      uses: anothrNick/github-tag-action@1.39.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        INITIAL_VERSION: v0.0.1
        WITH_V: true
